services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=authapp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql

  django:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/authapp_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
